### ISSUE TITLE
[BUG] Autorole disable 

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#107]
**Describe the bug**
Disable is saved in the database as a role. This does not disable the command but causes an error.

**Expected behavior**
Disable deletes the autorole entry in the database

**Additional context**
One should solve this problem sometime.

**Comment by ShowMeYourSkil** [comment]
We should include a check to see if this role exists at all.

@byNoobiYT I have tried it and the problem has not been fixed yet.

**Comment by byNoobiYT** [comment]
I'm unable to reproduce this behavior. Make sure you are running the latest commit of the master branch.

**Comment by ShowMeYourSkil** [comment]
Use pb!autorole to deactive autorole
