### ISSUE TITLE
[BUG] Set Autorole 

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#111]
**Type of Bug**

- [ ] Minor
- [ ] Medium
- [x] Important
- [ ] Critical

**Describe the bug**
> Describe the error as clear as possible

A Guild Owner wrote to me. He has Progen on his Guild since today and would like to use the command `autorole`. However, the command does not work. Below you can see the error. I will delete this user from Progen's Database, so an error not producted again.

**To Reproduce**
> Steps to reproduce the behavior:
1. Use pb!autorole `@zuverlässiger zuschauer`
2. New member has join his Guild
3. See error

**Expected behavior**
 > A clear and concise description of what you expected to happen.

-> New Member Join
-> New member has the role

**Additional context**
> Add any other context about the problem here.

**Images**
> If available, send a screenshot with the problem. It could help us.

![image](https://user-images.githubusercontent.com/39274150/102806904-fac49800-43bd-11eb-8d4c-558ac7a80894.png)

**Comment by ShowMeYourSkil** [comment]
SelfMember#canInteract(Role) und SelfMember#canInteract(Member) - fix

**Comment by ShowMeYourSkil** [comment]
Use pb!autorole to deactive autorole

**Comment by ShowMeYourSkil** [comment]
wrong issue

**Comment by ShowMeYourSkil** [comment]
@byNoobiYT how is it with a role perms check before we safe this change in the database? 
if: save in the database
else: Sorry, this role is to high for new member. Please choose a new role oder change the role settings.

**Comment by HGotthard** [comment]
What if the user adjusts the role after that?

> @byNoobiYT how is it with a role perms check before we safe this change in the database?
> if: save in the database
> else: Sorry, this role is to high for new member. Please choose a new role oder change the role settings.

What if the user adjusts the role after that?

**Comment by ShowMeYourSkil** [comment]
Oh true 😅

**Comment by ShowMeYourSkil** [comment]
I have to think about it.

**Comment by ShowMeYourSkil** [comment]
> > @byNoobiYT how is it with a role perms check before we safe this change in the database?
> > if: save in the database
> > else: Sorry, this role is to high for new member. Please choose a new role oder change the role settings.
> 
> What if the user adjusts the role after that?

I think i close this issue. I don't see any reason in this report
