### ISSUE TITLE
[Feature Request]  Unban

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#120]
**Category**
- [x] New Command 
- [ ] Enhancement

**Describe your Idea**
> Describe your suggestion for a new command.

Unban banned members

**Additional information**
> Smaller information that could be useful. 

Progenlog, Private message

**command steps**
> Steps as the command can be used.

1. 'pb!unban @ShowMeYourSkil Hello World"
2. 'Unban'

**Comment by byNoobiYT** [comment]
Duplicate of #98

**Comment by ShowMeYourSkil** [comment]
> Duplicate of #98

oh....

**Comment by ShowMeYourSkil** [comment]
How should the user specify the baned member if he is no longer on the guild?

**Comment by ShowMeYourSkil** [comment]
Duplicate of #98
