### ISSUE TITLE
Requirements document

### ISSUE THREAD

**Issue by mariosj99** [Progen-Dev/Progen#2]
Hello, I'm a third year student of Computer Science Department of Aristotle University in Greece. We have an assigment to contribute in an open source project. I was wondering if I could write the software requirements specification document of your project. Thank you!

**Comment by ShowMeYourSkil** [comment]
Hello, 
this is a discordbot with webinterface. If a link appears in the readme or documentation for the project, you must specify the MIT license and the development team 
Thanks a lot!

**Comment by ShowMeYourSkil** [comment]
Yes, we agree as long as the license is respected. We are very happy that a Discordbot running on 29 servers gets such an opportunity. If you have any questions, please comment on this issue. But you have to find out the requirements yourself. We have only given approximate information and have not yet implemented any software requirements.

Best wishes

**Comment by ShowMeYourSkil** [comment]
Good luck and fun working with Progen!
