### ISSUE TITLE
Discord invite link is invalid

### ISSUE THREAD

**Issue by byNoobiYT** [Progen-Dev/Progen#21]
**Describe the bug**
The discord guild invite link does not exist.

**To Reproduce**
1. Go to README.md
2. Then go to section `Support`
3. Click on `Join` 

**Expected behavior**
A valid guild invite to join support guild

**Please complete the following information:**
 - OS: Linux (Manjaro)

**Additional context**
404 Not found

**Error photo**
![photo](https://user-images.githubusercontent.com/47305525/77258768-1a872e00-6c7d-11ea-89c1-f448289dd8d1.png)

**Comment by ShowMeYourSkil** [comment]
YES I KNOW! In the next update they will be up to date again. here is a valid link => https://discord.gg/n7csqga

**Comment by ShowMeYourSkil** [comment]
or https://progen-bot.de

**Comment by byNoobiYT** [comment]
kinda toxic? xd

**Comment by mtorials** [comment]
Manjaro user! Love this os. Thanks again.

**Comment by ShowMeYourSkil** [comment]
Yes! Manjaro ist my faviorit os i love this os <3

**Comment by byNoobiYT** [comment]
So I'm writing a pull request about possible null pointer exceptions... Should I update the guild invite as well?

**Comment by ShowMeYourSkil** [comment]
no thanks. it is already on github. thank you for your help!

**Comment by byNoobiYT** [comment]
Soo... Can this issues will be closed due to fixing the support guild invite link?

**Comment by ShowMeYourSkil** [comment]
Byebye
