### ISSUE TITLE
[music] behavior of bot and play/start command

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#40]
**Describe the bug**
Command rewrite for Music

**To Reproduce**
New steps
1.pb!music Play blabla (delete pb!music start!)
2. Progen only leaves if channel is empty

**Comment by mtorials** [comment]
I won't rewrite the command for a few minor changes.....

**Comment by mtorials** [comment]
start command removed

**Comment by ShowMeYourSkil** [comment]
Thank you @mtorials
