### ISSUE TITLE
[New Command] Message logging

### ISSUE THREAD

**Issue by byNoobiYT** [Progen-Dev/Progen#43]
**Describe your Idea**
Enable message logging to see, which messages had been deleted.

**command steps**
1. `msglog enable #channel` - send log to #channel
2. `msglog disable` - disable message logging

**Expected behavior**
Progen sends a message into #channel with content of deleted message.

**Additional information**
/

**Webinterface Feature**
Maybe list deleted messages in PWI (guild specific)

**Comment by ShowMeYourSkil** [comment]
@byNoobiYT What should be logged?
