### ISSUE TITLE
PWI improvement when chaning prefix

### ISSUE THREAD

**Issue by Universumgames** [Progen-Dev/Progen#5]
it would be pretty helpful when changing the prefix, a notification appears in the PWI and the textbox is emptied. So that you don´t have to check in your server that the switch had worked

**Comment by ShowMeYourSkil** [comment]
@Universumgames YES that would be helpful!

**Comment by ShowMeYourSkil** [comment]
@Universumgames I am currently rewriting the pwi. There will be popup features or other stuff!
