### ISSUE TITLE
[BUG]  Mute applies to all guilds

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#51]
**Describe the bug**
I was muted on server A and could no longer write on the servers b and c because I was muted.

**To Reproduce**
1. pb!mute @ShowMeYourSkil 
2. write a message "blablabla"
3. Progen was sending a info message'
4. Go to Guild B or C
5. i can't send Messages. Progen muted me everywhere.

**Expected behavior**
Progen puts me only on server A and not mute everywhere:

**Please complete the following information:**
 -Discord Textchannels
**Additional context**
NOPE

**Error photo**
Because the messages are deleted I can't send a photo.

**Comment by byNoobiYT** [comment]
due to saving mutes in **one** database table btw

**Comment by byNoobiYT** [comment]
See [`CommandMute#toggle(String[], Message, TextChannel)`](https://github.com/Progen-Dev/Progen/blob/master/src/main/java/de/progen_bot/commands/moderator/CommandMute.java#L67-L90)

**Comment by mtorials** [comment]
We use files? Why?

**Comment by byNoobiYT** [comment]
Because someone implemented it using files afaik...

**Comment by mtorials** [comment]
Ok we should fix this I think. It does not really make sense to use files and a DB...

**Comment by byNoobiYT** [comment]
Should be resolved in #57
