### ISSUE TITLE
daily XP ranking

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#53]
Progen collects all written messages. After one day you can collect your coins with the command pb!coin or in the art. Spam should be protected with a spam protection of 10 seconds. For each message you get one coin. The points count only on the respective guild. A ranking would be nice too.

- [ ] Protection
- [ ] Command 
- [ ] Ranking
- [ ] Timer

**Comment by mtorials** [comment]
Isn't this basically the xp system? Where is the difference?

**Comment by mtorials** [comment]
Isn't this basically the xp system? Where is the difference?

**Comment by ShowMeYourSkil** [comment]
It's a different XP system. users can collect their coins with the command pb!coins and compare them in the ranking. The permanent activist on the guild is first place. The coins are only available on Guild a and not on Guild b. This is the difference to XP.

I would keep the current one anyway. and e.g. open a progen wide ranking via the pwi or per command.

**Comment by ShowMeYourSkil** [comment]
We feel that this feature does not fit with the current concept of progen. An idea would be to do a rewrite of our current XP system at some point.
