### ISSUE TITLE
Adding Shards to Progen

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#54]
Adding Shards to Progen

**Comment by mtorials** [comment]
What is a shard?

**Comment by byNoobiYT** [comment]
See [Discord Docs](https://discord.com/developers/docs/topics/gateway#sharding)

**Comment by mtorials** [comment]
Do we really need to care about that? I think this is really, really low on our priority list...

**Comment by byNoobiYT** [comment]
Discord requires sharding if the bot is on 1500+ Guilds and suggests at 1000+ Guilds. Although, JDA will shard automatically in a future version.

**Comment by ShowMeYourSkil** [comment]
So it's not worth it if it comes with the new JDA one way or another or how should I understand that? 🤔

**Comment by ShowMeYourSkil** [comment]
Bye
