### ISSUE TITLE
Migrate to JDK 11 LTS

### ISSUE THREAD

**Issue by byNoobiYT** [Progen-Dev/Progen#61]
Migrate JDK from 10 to 11 due to long-term support of version 11.

**Comment by byNoobiYT** [comment]
@Progen-Dev/core-dev should we include this already in version 1.0.0.7 of Progen?

**Comment by mtorials** [comment]
I think it is better to first release the bug fixes and then migrate.

**Comment by ShowMeYourSkil** [comment]
^I think so, too.

**Comment by ShowMeYourSkil** [comment]
See issue#63
