### ISSUE TITLE
Code rewrite

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#63]
This should become the issue where all steps for the rewrite are entered as checklist and planned.
### The rewritten code in the branch code-rewrite!! THANK YOU
<https://github.com/Progen-Dev/Progen/tree/Code-Rewrite>

- [ ] CommandHandler
- [ ] Database(MYSQL)
- [ ] Rewrite all Commands
- [x] Use JDK 11 LTS
- [x] update all maven Dependencys

The rewritten one should be soft coded. The code structure of the commands leaves some things to be desired. Just like the constant bugs in some commands.

**Comment by byNoobiYT** [comment]
see #64
