### ISSUE TITLE
[BUG] Warndelete

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#72]
User: Ruheloses

The warn is not deleted. Warning reason: test Command: pb!warndelete @Ruheloses test

**Comment by HGotthard** [comment]
The command deletes all warns not only one.  Its just warndelete <user>.

Maybe change it to delete only one by reason or number?

**Comment by ShowMeYourSkil** [comment]
reason ;)

**Comment by ShowMeYourSkil** [comment]
PR #74
