### ISSUE TITLE
[BUG] Mutelist

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#94]
**Describe the bug**
When I enter pb!mutelist on a guild that does not belong to me, an empty table appears instead of 'no mutes found'. 

**To Reproduce**
1. pb!muteslist
2. 
![image](https://user-images.githubusercontent.com/39274150/97670045-b4ba1a80-1a85-11eb-8635-42434a3672ea.png)

**Expected behavior**
`no mutes found`

**Please complete the following information:**
 - Discord

**Additional context**
> Add any other context about the problem here.

**Comment by HGotthard** [comment]
Any errors in the logs?

**Comment by byNoobiYT** [comment]
Works for me ![graphic](https://user-images.githubusercontent.com/47305525/97728056-60d52300-1ad1-11eb-8a34-c48990389b48.png)

**Comment by ShowMeYourSkil** [comment]
There is one for the Guild of Noobi. Not on the guild where I found the bug. It is not the official progen guild

![image](https://user-images.githubusercontent.com/39274150/97728619-0e483680-1ad2-11eb-99c8-f258aea4dcb4.png)

**Comment by ShowMeYourSkil** [comment]
The guild with the problem has database entries from users who do not exist or are not on the guild. I will manually delete the mutes from the guild.
