### ISSUE TITLE
[BUG] StarboardListener Missing Perms

### ISSUE THREAD

**Issue by ShowMeYourSkil** [Progen-Dev/Progen#95]
**Describe the bug**
The StarboardListener throws 2. errors. 

**To Reproduce**

**Expected behavior**
no error

**Please complete the following information:**
 - Are you self hosting Progen, if yes:
  - Java version:
  - error log

**Additional context**
- Missing Permssion: VIEW_CHANNEL
- Missing Permission: MESSAGE_WRITE

**Error photo**
![image](https://user-images.githubusercontent.com/39274150/97670367-580b2f80-1a86-11eb-8d46-6d88682f8f15.png)

**Comment by byNoobiYT** [comment]
Please fill out the given bug report template correctly.

**Comment by byNoobiYT** [comment]
Cannot reproduce, please update to latest version
